src/Web/Pages/Basket/Checkout.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.eShopWeb.ApplicationCore.Entities.OrderAggregate;
using Microsoft.eShopWeb.ApplicationCore.Interfaces;
using Microsoft.eShopWeb.Infrastructure.Identity;
using Microsoft.eShopWeb.Web.Interfaces;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Microsoft.eShopWeb.Web.Pages.Basket
{
    public class CheckoutModel : PageModel
    {
        private readonly IBasketService _basketService;
        private readonly IUriComposer _uriComposer;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IOrderService _orderService;
        private string _username = null;
        private readonly IBasketViewModelService _basketViewModelService;

        public CheckoutModel(IBasketService basketService,
            IBasketViewModelService basketViewModelService,
            IUriComposer uriComposer,
            SignInManager<ApplicationUser> signInManager,
            IOrderService orderService)
        {
            _basketService = basketService;
            _uriComposer = uriComposer;
            _signInManager = signInManager;
            _orderService = orderService;
            _basketViewModelService = basketViewModelService;
        }

        public BasketViewModel BasketModel { get; set; } = new BasketViewModel();

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost(Dictionary<string, int> items)
        {
            await SetBasketModelAsync();

            await _basketService.SetQuantities(BasketModel.Id, items);

            await _orderService.CreateOrderAsync(BasketModel.Id, new Address("123 Main St.", "Kent", "OH", "United States", "44240"));

            await _basketService.DeleteBasketAsync(BasketModel.Id);

            return RedirectToPage();
        }

        private async Task SetBasketModelAsync()
        {
            if (_signInManager.IsSignedIn(HttpContext.User))
            {
                BasketModel = await _basketViewModelService.GetOrCreateBasketForUser(User.Identity.Name);
            }
            else
            {
                GetOrSetBasketCookieAndUserName();
                BasketModel = await _basketViewModelService.GetOrCreateBasketForUser(_username);
            }
        }

        private void GetOrSetBasketCookieAndUserName()
        {
            if (Request.Cookies.ContainsKey(Constants.BASKET_COOKIENAME))
            {
                _username = Request.Cookies[Constants.BASKET_COOKIENAME];
            }
            if (_username != null) return;

            _username = Guid.NewGuid().ToString();
            var cookieOptions = new CookieOptions();
            cookieOptions.Expires = DateTime.Today.AddYears(10);
            Response.Cookies.Append(Constants.BASKET_COOKIENAME, _username, cookieOptions);
        }
    }
}

src/Web/Pages/Basket/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.eShopWeb.ApplicationCore.Interfaces;
using Microsoft.eShopWeb.Infrastructure.Identity;
using Microsoft.eShopWeb.Web.Interfaces;
using Microsoft.eShopWeb.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Microsoft.eShopWeb.Web.Pages.Basket
{
    public class IndexModel : PageModel
    {
        private readonly IBasketService _basketService;
        private const string _basketSessionKey = "basketId";
        private readonly IUriComposer _uriComposer;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private string _username = null;
        private readonly IBasketViewModelService _basketViewModelService;

        public IndexModel(IBasketService basketService,
            IBasketViewModelService basketViewModelService,
            IUriComposer uriComposer,
            SignInManager<ApplicationUser> signInManager)
        {
            _basketService = basketService;
            _uriComposer = uriComposer;
            _signInManager = signInManager;
            _basketViewModelService = basketViewModelService;
        }

        public BasketViewModel BasketModel { get; set; } = new BasketViewModel();

        public async Task OnGet()
        {
            await SetBasketModelAsync();
        }

        public async Task<IActionResult> OnPost(CatalogItemViewModel productDetails)
        {
            if (productDetails?.Id == null)
            {
                return RedirectToPage("/Index");
            }
            await SetBasketModelAsync();

            await _basketService.AddItemToBasket(BasketModel.Id, productDetails.Id, productDetails.Price, 1);

            await SetBasketModelAsync();

            return RedirectToPage();
        }

        public async Task OnPostUpdate(Dictionary<string, int> items)
        {
            await SetBasketModelAsync();
            await _basketService.SetQuantities(BasketModel.Id, items);

            await SetBasketModelAsync();
        }

        private async Task SetBasketModelAsync()
        {
            if (_signInManager.IsSignedIn(HttpContext.User))
            {
                BasketModel = await _basketViewModelService.GetOrCreateBasketForUser(User.Identity.Name);
            }
            else
            {
                GetOrSetBasketCookieAndUserName();
                BasketModel = await _basketViewModelService.GetOrCreateBasketForUser(_username);
            }
        }

        private void GetOrSetBasketCookieAndUserName()
        {
            if (Request.Cookies.ContainsKey(Constants.BASKET_COOKIENAME))
            {
                _username = Request.Cookies[Constants.BASKET_COOKIENAME];
            }
            if (_username != null) return;

            _username = Guid.NewGuid().ToString();
            var cookieOptions = new CookieOptions { IsEssential = true };
            cookieOptions.Expires = DateTime.Today.AddYears(10);
            Response.Cookies.Append(Constants.BASKET_COOKIENAME, _username, cookieOptions);
        }
    }
}

src/Web/Pages/Basket/Checkout.cshtml
@page
    @model CheckoutModel
@{
    ViewData["Title"] = "Checkout Complete";
}
<section class="esh-catalog-hero">
    <div class="container">
        <img class="esh-catalog-title" src="~/images/main_banner_text.png" />
    </div>
</section>

<div class="container">
    <h1>Thanks for your Order!</h1>

    <a asp-page="/Index">Continue Shopping...</a>
</div>

src/Web/Pages/Basket/Index.cshtml
@page "{handler?}"
@model IndexModel
@{
    ViewData["Title"] = "Basket";
}
<section class="esh-catalog-hero">
    <div class="container">
        <img class="esh-catalog-title" src="~/images/main_banner_text.png" />
    </div>
</section>

<div class="container">

    @if (Model.BasketModel.Items.Any())
    {
        <form method="post">
            <article class="esh-basket-titles row">
                <br />
                <section class="esh-basket-title col-xs-3">Product</section>
                <section class="esh-basket-title col-xs-3 hidden-lg-down"></section>
                <section class="esh-basket-title col-xs-2">Price</section>
                <section class="esh-basket-title col-xs-2">Quantity</section>
                <section class="esh-basket-title col-xs-2">Cost</section>
            </article>
            <div class="esh-catalog-items row">
                @for (int i = 0; i < Model.BasketModel.Items.Count; i++)
                {
                    var item = Model.BasketModel.Items[i];
                    <article class="esh-basket-items row">
                        <div>
                            <section class="esh-basket-item esh-basket-item--middle col-lg-3 hidden-lg-down">
                                <img class="esh-basket-image" src="@item.PictureUrl" />
                            </section>
                            <section class="esh-basket-item esh-basket-item--middle col-xs-3">@item.ProductName</section>
                            <section class="esh-basket-item esh-basket-item--middle col-xs-2">$ @item.UnitPrice.ToString("N2")</section>
                            <section class="esh-basket-item esh-basket-item--middle col-xs-2">
                                <input type="hidden" name="@("Items[" + i + "].Key")" value="@item.Id" />
                                <input type="number" class="esh-basket-input" min="1" name="@("Items[" + i + "].Value")" value="@item.Quantity" />
                            </section>
                            <section class="esh-basket-item esh-basket-item--middle esh-basket-item--mark col-xs-2">$ @Math.Round(item.Quantity * item.UnitPrice, 2).ToString("N2")</section>
                        </div>
                        <div class="row">

                        </div>
                    </article>
                    @*<div class="esh-catalog-item col-md-4">
                @item.ProductId
            </div>*@

                }

                <div class="container">
                    <article class="esh-basket-titles esh-basket-titles--clean row">
                        <section class="esh-basket-title col-xs-10"></section>
                        <section class="esh-basket-title col-xs-2">Total</section>
                    </article>

                    <article class="esh-basket-items row">
                        <section class="esh-basket-item col-xs-10"></section>
                        <section class="esh-basket-item esh-basket-item--mark col-xs-2">$ @Model.BasketModel.Total().ToString("N2")</section>
                    </article>

                    <article class="esh-basket-items row">
                        <section class="esh-basket-item col-xs-7"></section>
                        <section class="esh-basket-item col-xs-2">
                            @*<button class="btn esh-basket-checkout" name="name" value="" type="submit">[ Update ]</button>*@
                        </section>
                    </article>
                </div>

                <section class="esh-basket-item col-xs-push-8 col-xs-4">
                    <button class="btn esh-basket-checkout" name="updatebutton" value="" type="submit"
                            asp-page-handler="Update">
                        [ Update ]
                    </button>
                    <input type="submit" asp-page="Checkout"
                           class="btn esh-basket-checkout"
                           value="[ Checkout ]" name="action" />
                </section>

            </div>
        </form>
    }
    else
    {
        <div class="esh-catalog-items row">
            Basket is empty.
        </div>
    }
</div>